name: Bug report
description: 不具合の報告
title: "[Bug] "
labels: ["bug"]
body:
  - type: input
    id: summary
    attributes:
      label: 概要
      placeholder: 例) 惑星の軌道が更新されない
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: 再現手順
      placeholder: |
        1. ...
        2. ...
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: 影響度
      options:
        - blocker
        - critical
        - major
        - minor
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: 期待される挙動
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: ログ/スクリーンショット
